---
title: WordPress Basic Template
authors:
  - Paul Schnetzinger (@schnetzi)
  - Jay Rogers (@jaydrogers)
  - Dan Pastori (@danpastori)
description: A Wordpress Spin template.
repository: https://github.com/schnetzi/spin-template-wordpress
issues: https://github.com/schnetzi/spin-template-wordpress/issues
